name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        destination:
          - 'platform=macOS'
          - 'platform=macOS,variant=Mac Catalyst'
          - 'platform=iOS Simulator,name=iPhone 16,OS=latest'

    steps:
    - uses: actions/checkout@v4
    - name: List Schemes
      run: xcodebuild -showdestinations -scheme SimpleCommon
    - name: Build and Test
      run: xcodebuild test -scheme SimpleCommon -destination "${{ matrix.destination }}"
